version: "3.3"
services:
  wiftiket-app-web:
    container_name: wiftiket-app-web
    image: tubes-1:latest
    build: .
    volumes:
      - "./app:/var/www/html/app"
      - "./public:/var/www/html/public"
    env_file:
      - .env
    ports:
      - "8008:80"
    depends_on:
      - wiftiket-app-db

  wiftiket-app-db:
    container_name: wiftiket-app-db
    image: postgres:latest
    env_file:
      - .env
    restart: always
    volumes:
      - "./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"

  wiftiket-app-adminer:
    container_name: wiftiket-app-adminer
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    restart: always
    ports:
      - "5050:5050"
